src/qrisp/quantum_backtracking/backtracking_tree.py
Fixed several issues in the find_solution method and the Subtree class in backtracking_tree.py.
Otherwise, find_solution did not work if the solution was not obtained with the first QPE result.
=> Bugfix: find_solution method and Subtree class in backtracking_tree

setup.py
qiskit version set to 0.44 in setup.py
=> Update setup.py qiskit version

src/qrisp/qtypes/quantum_modulus.py
Added gate wrap in order to allow automatic uncomputation of QuantumModulus arithmetic
=> Add gate wrap to QuantumModulus arith.

documentation/source/general/papers/index.rst, documentation/source/index.rst
Added research section in the documentation
=> Added research in the documentation

src/qrisp/alg_primitives/arithmetic/ripple_mult.py, src/qrisp/permeability/qc_transformations/memory_management.py
More parts of the memory management algorithm are now numba based
=> Memory management upgrade

documentation/source/reference/Backend Interface/index.rst, src/qrisp/core/quantum_session.py, src/qrisp/interface/provider_backends/qiskit_backend.py, src/qrisp/interface/qunicorn/backend_server.py, src/qrisp/interface/virtual_backend.py, tests/test_qiskit_backend_client.py
Updated use of qiskit_aer (issue #80)
=> Qiskit backend update

src/qrisp/alg_primitives/__init__.py, src/qrisp/alg_primitives/switch_case.py, tests/test_qswitch.py
Implemented a function that performs the switch-case structure in super-position. An alternative implementation uses only logarithmic depth (but a lot of qubits).
=> implemented qswitch

src/qrisp/interface/qunicorn/backend_client.py, src/qrisp/interface/qunicorn/backend_server.py, src/qrisp/interface/request_manager.py
**Batching**
Adjust the feature for the changes happened in Qunicorn. 
The BackendClient  (`def run(self, qc, shots)` method) collects quantum circuits into batches of a specified size. Once the batch
is filled, it dispatches the batch for execution (`def dispatch(self)`). If the batch size is not yet met, the method logs
the current state and waits for more circuits to be added before dispatching. For more details, see docs for the function `run(self, qc, shots)` .
**Adjustments to Response Handling**
Since the qunicorn returns both "counts" and "probabilities", the BackendClient now includes an additional parameter `measurementValue`, which defines the format of the measurement results for the quantum circuit.
=> Adjust bachted feature in the BackendClient + refactoring for the BackendServer

documentation/source/general/tutorial/Quantum Alternating Operator Ansatz/MaxCut.rst, documentation/source/general/tutorial/Quantum Alternating Operator Ansatz/QUBO.rst
Fixed bugs in QAOA tutorials, more specifically in tutorial for MaxCut and QUBO.
=> fixed bugs in QAOA tutorials

documentation/source/general/tutorial/Jasp.rst, documentation/source/general/tutorial/index.rst
=> Added Jasp tutorial .rst file

src/qrisp/alg_primitives/mcx_algs/__init__.py, src/qrisp/alg_primitives/mcx_algs/balauca.py, src/qrisp/alg_primitives/mcx_algs/khattar.py, src/qrisp/core/gate_application_functions.py, tests/test_khattar_mcx.py
Implement the conditionally clean ancillae mcx both in standard qrisp and jax-compatible qrisp, add the corresponding documentation, add the test
=> Conditionally clean ancillae mcx (Khattar)

src/qrisp/alg_primitives/mcx_algs/khattar.py, src/qrisp/core/gate_application_functions.py, tests/jax_tests/test_dynamic_mcx.py, tests/test_khattar_mcx.py
Implement mcp based on khattar mcx, implement the test pipeline for it
Edit khattar mcx to use margolus gates and gidney mcx 
Swap ctrl qubits to reduce depht when using multiple margolus
=> Khattar mcp implementation

README.md, documentation/source/reference/Core/QuantumArray.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.concatenate.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.decoder.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.encode.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.encoder.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.flatten.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.init_from.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.init_state.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.ravel.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.reshape.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.set_shape.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.swapaxes.rst, documentation/source/reference/Core/generated/qrisp.QuantumArray.transpose.rst, src/qrisp/alg_primitives/arithmetic/matrix_multiplication.py, src/qrisp/alg_primitives/mcx_algs/khattar.py, src/qrisp/core/gate_application_functions.py, src/qrisp/core/quantum_array.py, src/qrisp/core/quantum_variable.py, src/qrisp/core/session_merging_tools.py, src/qrisp/jasp/jasp_expression/centerclass.py, src/qrisp/jasp/tracing_logic/dynamic_qubit_array.py, src/qrisp/jasp/tracing_logic/qaching.py, src/qrisp/misc/utility.py, src/qrisp/qtypes/quantum_string.py, tests/jax_tests/test_jasp_quantum_array.py, tests/test_matrix_multiplication_example.py, tests/test_quantum_array.py, tests/test_string_test.py, tests/test_uncomputation_example.py
Ported QuantumArrays to be Jasp compatible and improved the readme file a bit
=> Quantum array jasp port

src/qrisp/jasp/interpreter_tools/interpreters/catalyst_interpreter.py, src/qrisp/jasp/optimizers/spsa.py
Fix for https://github.com/eclipse-qrisp/Qrisp/issues/153
=> some fixes for making kernelized functions qir compatible

src/qrisp/operators/qubit/qubit_operator.py
This PR added 2nd order trotterization as an optional parameter `order`, where the 2nd order Trotter-Suzuki formula is given by
$$
e^{it(A+B)} \approx(e^{i\frac{t}{2N}A} e^{i\frac{t}{N}B} e^{i\frac{t}{2N}A})^N 
$$
=> 2nd order trotterization option

documentation/source/reference/Jasp/Resource Estimation.rst, documentation/source/reference/Jasp/Ressource Estimation.rst, documentation/source/reference/Jasp/index.rst, src/qrisp/jasp/evaluation_tools/__init__.py, src/qrisp/jasp/evaluation_tools/profiler.py, src/qrisp/jasp/interpreter_tools/interpreters/__init__.py, src/qrisp/jasp/interpreter_tools/interpreters/profiling_interpreter.py, src/qrisp/jasp/jasp_expression/centerclass.py, tests/jax_tests/test_count_ops.py
Implemented the ``count_ops`` decorator, which can be used to determine the gate-count for very large algorithms.
=> Profiling interpreter

src/qrisp/alg_primitives/amplitude_amplification.py, src/qrisp/alg_primitives/iterative_qae.py, src/qrisp/algorithms/grover/grover_tools.py
Reintroduced IterationEnvironment in amplitude amplification and Grover's algorithm in non-tracing mode
=> amplitude amplification upgrades

src/qrisp/algorithms/qite.py, tests/jax_tests/test_jasp_qite.py
Adds a jasp-compatible version of QITE (both GC and HOPF).
=> Add jasp QITE

src/qrisp/jasp/evaluation_tools/buffered_quantum_state.py, src/qrisp/jasp/evaluation_tools/jaspification.py, src/qrisp/jasp/evaluation_tools/profiler.py, src/qrisp/jasp/interpreter_tools/abstract_interpreter.py, src/qrisp/jasp/interpreter_tools/interpreters/profiling_interpreter.py, src/qrisp/jasp/jasp_expression/centerclass.py, tests/jax_tests/test_count_ops.py, tests/jax_tests/test_terminal_sampling.py
Note: Pipeline failed due to Sympy breaking change, which is fixed in the main branch
=> Implemented measurement behavior specification and did some restructurings, which accelerates count_ops compilation for large static Jasprs

src/qrisp/__init__.py, src/qrisp/alg_primitives/switch_case.py, src/qrisp/environments/__init__.py, src/qrisp/environments/custom_control_environment.py, src/qrisp/environments/custom_inversion_environment.py, src/qrisp/jasp/jasp_expression/centerclass.py, src/qrisp/jasp/jasp_expression/environment_collection.py, src/qrisp/jasp/jasp_expression/inv_transform.py, src/qrisp/jasp/tracing_logic/qaching.py, tests/jax_tests/test_custom_inverse.py
Implemented a decorator that allows users to specify customized inversion behavior (similar to customized control behavior). This is important because some algorithmic primitives contain measurements but still well defined inverses (such as the Gidney Logical AND).
=> Custom inversion

src/qrisp/qtypes/quantum_float.py
More efficient calculation of size of QuantumFloat for add/sub
=> QuantumFloat upgrades

.github/workflows/qrisp_test.yml, documentation/source/reference/Backend Interface/QiskitRuntimeBackend.rst, documentation/source/reference/Backend Interface/generated/qrisp.interface.QiskitRuntimeBackend.close_session.rst, src/qrisp/interface/provider_backends/qiskit_backend.py, tests/test_qiskit_backend_client.py
Updated QiskitBackend and QiskitRuntimeBackend based on SamplerV2; Added additional keywords for QiskitRuntimeBackend (can be used in "job" and "session" mode)
=> Qiskit backends updates

src/qrisp/core/compilation.py
Tiny PR which removes an unused snippet from `qrisp/core/compilation.py`.
=> Removed unused snippet.
